import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Every cheatsheet is a markdown file under src/content/sheets/<category>/.
// Nav + taxonomy are driven by the `category` frontmatter, not the folder.
const sheets = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/sheets' }),
  schema: z.object({
    title: z.string(),
    description: z.string().default(''),
    category: z.string(),
    tags: z.array(z.string()).default([]),
    tools: z.array(z.string()).default([]),
    difficulty: z.enum(['beginner', 'intermediate', 'advanced']).default('intermediate'),
    // Accept a quoted string or a bare YAML date; always expose YYYY-MM-DD.
    updated: z
      .union([z.string(), z.date()])
      .optional()
      .transform((v) => (v instanceof Date ? v.toISOString().slice(0, 10) : v)),
    source: z.string().optional(),
    // When set, the sheet embeds/links a PDF that lives in public/pdfs/<pdf>.
    pdf: z.string().optional(),
    draft: z.boolean().default(false),
  }),
});

// Mirror of PayloadsAllTheThings (MIT, swisskyrepo). Generated by
// scripts/sync-payloads.py — do not hand-edit files under src/content/payloads.
const payloads = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/payloads' }),
  schema: z.object({
    title: z.string(),
    topic: z.string(),
    topicSlug: z.string(),
    sourcePath: z.string(),
    sourceUrl: z.string(),
    sha: z.string(),
    isReadme: z.boolean().default(false),
  }),
});

export const collections = { sheets, payloads };
