import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Every cheatsheet is a markdown file under src/content/sheets/<category>/.
// Nav + taxonomy are driven by the `category` frontmatter, not the folder.
const sheets = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/sheets' }),
  schema: z.object({
    title: z.string(),
    description: z.string().default(''),
    category: z.string(),
    // Optional second-level grouping shown as sub-sections on a busy
    // category page (Active Directory has 130+ sheets). Derived from the
    // source vault path by scripts/stamp-subcategory.py.
    subcategory: z.string().optional(),
    tags: z.array(z.string()).default([]),
    tools: z.array(z.string()).default([]),
    difficulty: z.enum(['beginner', 'intermediate', 'advanced']).default('intermediate'),
    // Accept a quoted string or a bare YAML date; always expose YYYY-MM-DD.
    updated: z
      .union([z.string(), z.date()])
      .optional()
      .transform((v) => (v instanceof Date ? v.toISOString().slice(0, 10) : v)),
    source: z.string().optional(),
    // Third-party provenance. `source` above records only the vault path a sheet
    // was imported from, which says nothing about who wrote it; these fields
    // record the real upstream so the page can credit it. Set them together.
    // `none` means the upstream publishes no licence at all — that grants no
    // right to copy, so such a sheet must be a link-only stub, not a mirror.
    upstreamName: z.string().optional(),
    upstreamUrl: z.string().url().optional(),
    upstreamAuthor: z.string().optional(),
    upstreamLicense: z.enum(['MIT', 'BSD-2-Clause', 'BSD-3-Clause', 'Apache-2.0', 'none', 'proprietary']).optional(),
    upstreamRelation: z.enum(['verbatim', 'derived', 'inspired', 'link-only']).optional(),
    // The notice MIT/BSD/Apache require to travel with a copy.
    upstreamCopyright: z.string().optional(),
    // When set, the sheet embeds/links a PDF that lives in public/pdfs/<pdf>.
    pdf: z.string().optional(),
    draft: z.boolean().default(false),
  }),
});

// Mirror of PayloadsAllTheThings (MIT, swisskyrepo). Generated by
// scripts/sync-payloads.py — do not hand-edit files under src/content/payloads.
const payloads = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/payloads' }),
  schema: z.object({
    title: z.string(),
    topic: z.string(),
    topicSlug: z.string(),
    sourcePath: z.string(),
    sourceUrl: z.string(),
    sha: z.string(),
    isReadme: z.boolean().default(false),
  }),
});

// Mirror of InternalAllTheThings (swisskyrepo). Generated by
// scripts/sync-internal.py — do not hand-edit files under src/content/internal.
const internal = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/internal' }),
  schema: z.object({
    title: z.string(),
    section: z.string(),
    sectionSlug: z.string(),
    sourcePath: z.string(),
    sourceUrl: z.string(),
    sha: z.string(),
    isIndex: z.boolean().default(false),
  }),
});

export const collections = { sheets, payloads, internal };
